site_name: YAP Prolog Reference Manual
site_url: https://www.dcc.fc.up.pt/YAP
use_directory_urls: false
theme:
  name: 'readthedocs'
  highlightjs: true
  hljs_languages:
    - prolog
    - c
    - python
    - c++
    - java
    - javascript
    - R
  logo: 'img/favicon.ico'
plugins:
  - search
  - autorefs
  - mkdoxy:
      enabled: False
      doxy-bin-path: "echo"
      projects:
        YAP:
          src-dirs: ../../
          full-doc: True
          template-dir: templates-custom
      save-api: .
      emojis-enabled: True

markdown_extensions:
   - attr_list
   - def_list


nav:
   - Home: index.md
   - INSTALL: INSTALL.md
   - Calling YAP: CALLING_YAP.md
   -   Built-ins:
       - Core: group__Builtins.md
       - Input-Output: group__InputOutput.md
   - Programming: group__YAPProgramming.md
   - Extensions: group__YapExtensions.md
   - Library: group__YAPLibrary.md
   - Available Packages: group__YAPPackages.md
   - Foreign Language Interface : group__YAPAPI.md
   - Indices:
       - YAP/modules.md
       - YAP/namespaces.md
       - YAP/links.md
       - Implementation:
           - YAP/classes.md
           - YAP/files.md

