site_name: 'YAP'
theme: 'readthedocs'
markdown_extensions:
use_directory_urls: false
plugins:
  - search
  - awesome-pages:
      filename: .index
      disable_auto_arrange_index: false
      collapse_single_pages: true